import Button from '@/components/atoms/Button';
import Chip from '@/components/atoms/Chip';
import SVGClient from '@/components/atoms/SVGClient';
import CTA from '@/components/organisms/CTA';
import FaqV1 from '@/components/organisms/FaqV1';
import Testimonial from '@/components/organisms/Testimonial';
import { Icon } from '@iconify/react';
import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
	title: 'iExcelo - Landing',
	description: 'Generated by create next app',
};

/* eslint-disable @next/next/no-img-element */
export default function Home() {
	return (
		<main className='bg-white'>
			<section className='bg-[url(/images/background-pattern.png)] bg-center bg-cover flex justify-end h-[122vh]'>
				<div className='max-w-[1300px] flex flex-col gap-[2rem] justify-end w-[90%] mx-auto'>
					<div className='flex items-center justify-between'>
						<div className='max-w-[40rem]'>
							<h1 className='mb-[1rem] text-[3.25rem] font-[600] tracking-[-1.04px] text-[#101928] leading-[3.5rem]'>
								Revise Smarter, Practice Harder and{' '}
								<span className='text-[#E32E89] z-[3] relative'>
									Excel{' '}
									<SVGClient
										className='absolute top-0 left-0 translate-x-[20%] translate-y-[10%] z-[-1]'
										src='/svg/hand-drawn-accents.svg'
									/>
								</span>
								<br /> in every Exam!
							</h1>
							<p className='mb-[1.5rem] text-[1.5rem] max-w-[33rem] leading-[2rem] tracking-[-.48px] text-[#667185] font-[500]'>
								Modern online revision that makes exam prep simpler and smarter
							</p>
							<Button>
								Get Started
								<Icon
									icon='hugeicons:arrow-right-02'
									height={'1.5rem'}
									width={'1.5rem'}
								/>
							</Button>
						</div>
						<img
							src={'/images/hero-img-1.png'}
							alt='Hero Image 1'
							className='max-w-[36.625rem] h-[34.5rem]'
							loading='lazy'
						/>
					</div>
					<img
						src={'/images/hero-img-2.png'}
						alt='Hero Image 2'
						loading='lazy'
					/>
				</div>
			</section>

			<section className='py-[6rem] max-w-[1300px] mx-auto w-[90%]'>
				<Chip
					name='Our Benefits'
					iconPath='hugeicons:star'
				/>
				<div className='mt-[2rem] flex justify-between items-center'>
					<div className='w-[47%]'>
						<h2 className='text-[2.75rem] leading-[3rem] w-[90%] tracking-[-.88px] font-[600] text-[#101928] mb-[.5rem]'>
							Why Students Choose Us to Excel.
						</h2>
						<p className='text-[#667185] font-[400] text-[1.125rem] leading-[1.75rem] mb-[2.5rem]'>
							From top-level exam questions to smart revision tools, we make
							preparation simpler, faster, and more effective.
						</p>
						<div className=' gap-[1.5rem_1rem] grid grid-cols-1 md:grid-cols-2'>
							{[
								{
									title: 'Practice with the Best',
									content: `From top-level exam questions to smart revision tools, we make preparation simpler, faster, and more effective.`,
									icon: 'hugeicons:notebook-01',
								},
								{
									title: 'Learn with Confidence',
									content: `Every answer comes with expert explanations, giving you reliable insights and a deeper understanding of each concept.`,
									icon: 'hugeicons:book-open-02',
								},
								{
									title: 'Know Where You Stand',
									content: `Topic-based summaries help you identify what you've mastered and where you need more practice fast.`,
									icon: 'hugeicons:board-math',
								},
								{
									title: 'Revise Smarter, Not Harder',
									content: `Structured study support ensures you focus on the right questions, saving time while boosting exam performance.`,
									icon: 'hugeicons:brain',
								},
							]?.map((item, index) => (
								<div
									key={`__box__item__${index}`}
									style={{
										boxShadow:
											'0 0 0 1px rgba(0, 0, 0, 0.06), 0 5px 22px 0 rgba(0, 0, 0, 0.04)',
									}}
									className='p-[1rem] flex flex-col gap-[1rem] bg-white rounded-[.75rem] overflow-hidden'
								>
									<span className='p-[.75rem] w-fit bg-[#E6F2FF] rounded-[.5rem]'>
										<Icon
											icon={item?.icon}
											height={'1.05rem'}
											width={'1.05rem'}
											color='#007FFF'
										/>
									</span>
									<h4 className='text-[#101928] text-[1.25rem] leading-[1.75rem] font-[500] tracking-[.4px]'>
										{item?.title}
									</h4>
									<p className='leading-[1.25rem] text-[#667185] w-[90%] font-[400] text-[.875rem]'>
										{item?.content}
									</p>
								</div>
							))}
						</div>
					</div>
					<figure className='w-[47%]'>
						<img
							src={`/images/landing-img-1.png`}
							alt='Landing Image 1'
						/>
					</figure>
				</div>
			</section>

			<section className='py-[6rem] max-w-[1300px] mx-auto w-[90%]'>
				<div className='w-fit mx-auto mb-[2rem]'>
					<Chip
						name='Our Features'
						iconPath='hugeicons:sparkles'
					/>
				</div>
				<h2 className='text-[2.75rem] text-center leading-[3rem] tracking-[-.88px] font-[600] text-[#101928] mb-[.5rem]'>
					Where Success Meets Innovation.
				</h2>
				<p className='text-[#667185] font-[400] text-[1.125rem] text-center leading-[1.75rem] mb-[2.5rem]'>
					Revise smarter, support others through giveback, and unlock new
					opportunities with our affiliate program
				</p>
				<div className='flex gap-[1rem] justify-between'>
					{[
						{
							title: 'Master Every Question',
							icon: 'hugeicons:book-open-02',
							content: `Access curated past exam questions designed to help you practice smarter and build confidence for the real test.`,
							href: 'https://johnex.com',
						},
						{
							title: 'Support Students',
							icon: 'hugeicons:healtcare',
							content: `Our Giveback program connects sponsors and learners to make education accessible for everyone.`,
							href: 'https://johnex.com',
						},
						{
							title: 'Earn as You Share',
							icon: 'hugeicons:affiliate',
							content: `Our affiliate program gives you a simple way to earn by sharing the power of smart learning.`,
							href: 'https://johnex.com',
						},
					]?.map((item, index) => (
						<div
							key={`__item__${item?.title}__${index}`}
							className='flex-1 rounded-[.75rem] overflow-hidden'
							style={{
								boxShadow:
									'0 0 0 1px rgba(0, 0, 0, 0.06), 0 5px 22px 0 rgba(0, 0, 0, 0.04)',
							}}
						>
							<figure className='h-[15.25rem] overflow-hidden'>
								<img
									src={`/images/landing-img-${index + 2}.png`}
									alt={`Landing image ${index + 2}`}
								/>
							</figure>
							<div className='p-[1.25rem_1.25rem_1.25rem_2rem]'>
								<div className='flex items-center mb-[.75rem] gap-[.5rem]'>
									<Icon
										icon={item?.icon}
										height={'1.25rem'}
										width={'1.25rem'}
										color='#00356B'
									/>
									<span className='leading-[1.75rem] text-[1.25rem] font-[600] tracking-[-.4px] text-[#00356B]'>
										{item?.title}
									</span>
								</div>
								<p className='text-[#667185] font-[400] text-[1.125rem] leading-[1.75rem] mb-[.5rem]'>
									{item?.content}
								</p>
								<Link
									target='_blank'
									className='block text-[#E32E89] text-[.75rem] font-[600] leading-[1.25rem]'
									href={item?.href}
								>
									Learn More
								</Link>
							</div>
						</div>
					))}
				</div>
			</section>

			<section className='py-[4rem] max-w-[1300px] mx-auto w-[90%]'>
				<div className='w-fit mx-auto mb-[2rem]'>
					<Chip
						name='Testimonials'
						iconPath='hugeicons:megaphone-02'
					/>
				</div>
				<h2 className='text-[2.75rem] text-center leading-[3rem] tracking-[-.88px] font-[600] text-[#101928] mb-[.5rem]'>
					What Our Users Say
				</h2>
				<p className='text-[#667185] font-[400] text-[1.125rem] text-center leading-[1.75rem] mb-[2.5rem]'>
					Used by thousands of students, parents and partners
				</p>
				<Testimonial />
			</section>

			<FaqV1 />

			<CTA />
		</main>
	);
}
